apiVersion: v1
kind: Service
metadata:
  name: rninfosoft-flask-service
spec:
  type: NodePort
  selector:
    app: rninfosoft-flask
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007

